# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildwindows:
    runs-on: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Build Project
        run: |
          cd $env:GITHUB_WORKSPACE
          bazel build :ugly-tests
          bazel build :uglycli
          bazel-bin\ugly-tests
  
  buildlinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: ghcr.io/cultlang/buildbox:1.0
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Build Project
        run: |
          cd $GITHUB_WORKSPACE
          bazel build :ugly-tests
          bazel build :uglycli
          ./bazel-bin/ugly-tests
          mkdir bazel-bin/ugly
          mv bazel-bin/uglycli bazel-bin/ugly
          cp -R src bazel-bin/ugly/include
          tar -czf bazel/bin/ugly$GITHUB_SHA.tar.gz bazel-bin/ugly
      - uses: actions/upload-artifact@v2
        with:
          name: ugly-linux-amd64
          path: $GITHUB_WORKSPACE/bazel-bin/ugly$GITHUB_SHA.tar.gz
          
